/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Estado del servicio y proveedor GenAI activo (API-01).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ideas/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Demo Ideas
         * @description Ideas demo del seed (design §9.3) — sin tocar la DB.
         */
        get: operations["list_demo_ideas_api_ideas_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Historial de proyectos (P1-ready, design §5.4).
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Crea un proyecto en estado ``IDEA`` (CAP-01).
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Brief
         * @description Captura el brief (transición IDEA → BRIEF_READY; guard CAP-02/03).
         */
        post: operations["submit_brief_api_projects__project_id__brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Project Detail
         * @description Detalle del proyecto: brief, estado y voz aplicada (§5.4).
         */
        get: operations["project_detail_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trace
         * @description Traza del run, redactada antes de responder (TRC-02, RNF-04).
         */
        get: operations["run_trace_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Run
         * @description GENERATED → RECOMMENDED | REVISION_REQUIRED | EVALUATION_PARTIAL.
         */
        post: operations["evaluate_run_api_runs__run_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description BRIEF_READY → GENERATING → GENERATED | GENERATION_FAILED (RF-02).
         */
        post: operations["generate_api_projects__project_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/retry-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Generate
         * @description GENERATION_FAILED → GENERATING → GENERATED (RNF-03: run NUEVO).
         */
        post: operations["retry_generate_api_projects__project_id__retry_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Candidate
         * @description Edición humana: invalida evaluación/visual (APPR-02/03, FSM-03).
         */
        post: operations["edit_candidate_api_candidates__candidate_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/request-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Revision
         * @description RECOMMENDED → REVISION_REQUIRED con razón editorial (APPR-01).
         */
        post: operations["request_revision_api_candidates__candidate_id__request_revision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Candidate
         * @description Aprobación humana con razón; sin blockers activos (APPR-01).
         */
        post: operations["approve_candidate_api_candidates__candidate_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/visual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Visual
         * @description APPROVED → VISUAL_DRAFT (contrato derivado de la tesis, VIS-01/03).
         */
        post: operations["generate_visual_api_candidates__candidate_id__visual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/publish-simulated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Simulated
         * @description VISUAL_READY → SIMULATED_PUBLISHED (SIM-01/02/04; recibo local).
         */
        post: operations["publish_simulated_api_candidates__candidate_id__publish_simulated_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visuals/{visual_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Visual
         * @description VISUAL_DRAFT → VISUAL_READY con aprobación humana razonada (VIS-06).
         */
        post: operations["approve_visual_api_visuals__visual_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visuals/{visual_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Visual
         * @description VISUAL_DRAFT → VISUAL_REVISION_REQUIRED con razón (VIS-06).
         */
        post: operations["reject_visual_api_visuals__visual_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visuals/{visual_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Visual
         * @description VISUAL_REVISION_REQUIRED → VISUAL_DRAFT (VIS-06).
         */
        post: operations["regenerate_visual_api_visuals__visual_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visuals/{visual_id}/svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visual Svg
         * @description SVG del visual — path desde la DB, nunca del usuario (§13.5).
         */
        get: operations["visual_svg_api_visuals__visual_id__svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Blocker
         * @description Blocker de evidencia/seguridad (EVAL-05, design §4.5).
         */
        Blocker: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Detail */
            detail?: string | null;
        };
        /**
         * BriefIn
         * @description Brief editorial canónico (design §5.5; capture CAP-02/03/05).
         *
         *     La tesis MUST ser única y no vacía; la obligación de al menos una
         *     evidencia la gobierna el guard de la FSM (design §4.2 transición 1),
         *     no este schema.
         */
        BriefIn: {
            /** Thesis */
            thesis: string;
            /**
             * Audience
             * @default
             */
            audience: string;
            /**
             * Objective
             * @default
             */
            objective: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceItem"][];
            /** Constraints */
            constraints?: string[];
        };
        /**
         * CandidateContent
         * @description Contenido editable de un candidato (APPR-02).
         */
        CandidateContent: {
            /** Hook */
            hook: string;
            /** Body */
            body: string;
            /** Cta */
            cta: string;
        };
        /**
         * CandidateEdit
         * @description Request de ``POST /api/candidates/{id}/edit`` (design §5.4).
         */
        CandidateEdit: {
            content: components["schemas"]["CandidateContent"];
        };
        /**
         * CandidateOut
         * @description Candidato del contrato API: suma id, versión y evaluación (design §5.5).
         */
        CandidateOut: {
            /**
             * Angle
             * @enum {string}
             */
            angle: "problem-story" | "practical-framework" | "argued-position";
            /** Hook */
            hook: string;
            /** Body */
            body: string;
            /** Cta */
            cta: string;
            /** Claims */
            claims?: components["schemas"]["ClaimOut"][];
            /** Id */
            id: number;
            /**
             * Content Version
             * @default 1
             */
            content_version: number;
            evaluation?: components["schemas"]["EvaluationSummary"] | null;
            /** Decision */
            decision?: string | null;
        };
        /**
         * CandidateScore
         * @description Score desglosado de un candidato (design §5.5, EVAL-01/02/03).
         */
        CandidateScore: {
            /** Candidate Id */
            candidate_id: number;
            dimensions: components["schemas"]["DimensionRatings"];
            penalties?: components["schemas"]["Penalties"];
            /** Score Final */
            score_final: number;
            /** Blockers */
            blockers?: components["schemas"]["Blocker"][];
        };
        /**
         * ClaimOut
         * @description Claim del candidato con soporte declarado (GEN-04).
         *
         *     ``support`` referencia una evidencia del brief, ``author_opinion`` o
         *     ``needs_review``; la existencia real del soporte la valida el dominio
         *     (design §5.5).
         */
        ClaimOut: {
            /** Text */
            text: string;
            /** Support */
            support: string;
        };
        /**
         * DecisionOut
         * @description Decisión de la regla reproducible (design §4.5, EVAL-06).
         */
        DecisionOut: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "RECOMMENDED" | "REVISION_REQUIRED";
            /** Best Candidate Id */
            best_candidate_id?: number | null;
            /** Reason */
            reason: string;
            /**
             * Brief Needs Revision
             * @default false
             */
            brief_needs_revision: boolean;
        };
        /**
         * DemoIdeaOut
         * @description Idea demo ofrecida por ``GET /api/ideas/demo`` (design §9.3).
         */
        DemoIdeaOut: {
            /** Id */
            id: string;
            /** Raw Idea */
            raw_idea: string;
            /**
             * Default Audience
             * @default
             */
            default_audience: string;
            /**
             * Default Objective
             * @default
             */
            default_objective: string;
        };
        /**
         * DimensionRatings
         * @description Las 6 dimensiones de la fórmula §7.2 (design §4.4).
         */
        DimensionRatings: {
            hook: components["schemas"]["DimensionScore"];
            niche_relevance: components["schemas"]["DimensionScore"];
            specificity_evidence: components["schemas"]["DimensionScore"];
            clarity: components["schemas"]["DimensionScore"];
            conversation_potential: components["schemas"]["DimensionScore"];
            voice_fit: components["schemas"]["DimensionScore"];
        };
        /**
         * DimensionScore
         * @description Nota ordinal 0-5 con cita y regla de rúbrica (EVAL-02/03).
         *
         *     Una nota sin ``quote`` y ``rubric_rule`` es inválida (design §4.4).
         */
        DimensionScore: {
            /** Rating */
            rating: number;
            /** Quote */
            quote: string;
            /** Rubric Rule */
            rubric_rule: string;
        };
        /**
         * ErrorBody
         * @description Envelope de error: ``{"error": {"code", "message", "details"}}``.
         */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * ErrorDetail
         * @description Detalle de error único: código + mensaje accionable + detalles.
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * EvaluationOut
         * @description Respuesta de ``POST /api/runs/{run_id}/evaluate`` (design §5.4).
         */
        EvaluationOut: {
            /** Candidate Scores */
            candidate_scores: components["schemas"]["CandidateScore"][];
            decision: components["schemas"]["DecisionOut"];
        };
        /**
         * EvaluationSummary
         * @description Resumen de evaluación incrustado en ``CandidateOut`` (design §5.5).
         */
        EvaluationSummary: {
            /** Score Final */
            score_final: number;
            /** Decision */
            decision?: string | null;
        };
        /**
         * EvidenceItem
         * @description Afirmación del brief clasificada por tipo (CAP-05, design §5.5).
         */
        EvidenceItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Type
             * @enum {string}
             */
            type: "known_facts" | "author_opinions" | "open_questions";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthOut
         * @description Respuesta de ``GET /api/health``.
         */
        HealthOut: {
            /**
             * Status
             * @default ok
             * @constant
             * @enum {string}
             */
            status: "ok";
            /** Provider */
            provider?: string | null;
            /**
             * Configured Provider
             * @default demo
             * @enum {string}
             */
            configured_provider: "demo" | "openai";
            /**
             * Openai Configured
             * @default false
             */
            openai_configured: boolean;
        };
        /**
         * Penalties
         * @description Penalizaciones de la fórmula (EVAL-04).
         */
        Penalties: {
            /**
             * Risk
             * @default 0
             */
            risk: number;
            /**
             * Generic
             * @default 0
             */
            generic: number;
        };
        /**
         * ProjectCreate
         * @description Request de ``POST /api/projects`` (design §5.4; CAP-01).
         */
        ProjectCreate: {
            /** Raw Idea */
            raw_idea: string;
            /** Title */
            title?: string | null;
        };
        /**
         * ProjectDetailOut
         * @description Proyecto con brief y voz aplicada (design §5.4).
         */
        ProjectDetailOut: {
            /** Id */
            id: number;
            /** Raw Idea */
            raw_idea: string;
            /** Title */
            title?: string | null;
            /**
             * Status
             * @default IDEA
             */
            status: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            brief?: components["schemas"]["BriefIn"] | null;
            voice_profile?: components["schemas"]["VoiceProfileOut"] | null;
        };
        /**
         * ProjectOut
         * @description Proyecto (vista de lista, P1-ready — design §5.4/§9.1).
         */
        ProjectOut: {
            /** Id */
            id: number;
            /** Raw Idea */
            raw_idea: string;
            /** Title */
            title?: string | null;
            /**
             * Status
             * @default IDEA
             */
            status: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * PublicationOut
         * @description Respuesta de ``POST /api/candidates/{id}/publish-simulated`` (§5.4).
         */
        PublicationOut: {
            receipt: components["schemas"]["ReceiptOut"];
            /** Candidate Id */
            candidate_id: number;
            /** Visual Id */
            visual_id: number;
            /**
             * Mode
             * @default simulated
             * @constant
             * @enum {string}
             */
            mode: "simulated";
            /**
             * Status
             * @default SIMULATED_PUBLISHED
             * @constant
             * @enum {string}
             */
            status: "SIMULATED_PUBLISHED";
        };
        /**
         * ReasonIn
         * @description Razón editorial obligatoria (APPR-01/04, VIS-06).
         */
        ReasonIn: {
            /** Reason */
            reason: string;
        };
        /**
         * ReceiptOut
         * @description Recibo local de publicación simulada (design §5.5, SIM-02).
         *
         *     ``remote_id`` es ``None`` SIEMPRE en modo simulado: jamás un ID remoto
         *     inventado. ``mode``/``status``/``notice`` son literales cerrados.
         */
        ReceiptOut: {
            /** Id */
            id: number;
            /**
             * Mode
             * @default simulated
             * @constant
             * @enum {string}
             */
            mode: "simulated";
            /**
             * Status
             * @default SIMULATED_PUBLISHED
             * @constant
             * @enum {string}
             */
            status: "SIMULATED_PUBLISHED";
            /** Candidate Id */
            candidate_id: number;
            /** Visual Id */
            visual_id: number;
            /** Created At */
            created_at: string;
            /**
             * Notice
             * @default no se envió contenido a LinkedIn
             * @constant
             * @enum {string}
             */
            notice: "no se envió contenido a LinkedIn";
            /** Remote Id */
            remote_id?: null;
        };
        /**
         * RunDetailOut
         * @description Traza completa de una ejecución, ya redactada (TRC-01/02).
         */
        RunDetailOut: {
            run: components["schemas"]["RunOut"];
            /** Trace Events */
            trace_events?: components["schemas"]["TraceEventOut"][];
            brief?: components["schemas"]["BriefIn"] | null;
            voice_profile?: components["schemas"]["VoiceProfileOut"] | null;
        };
        /**
         * RunOut
         * @description Respuesta de generate/retry-generate: run + candidatos (design §5.4).
         */
        RunOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Status */
            status: string;
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Schema Version */
            schema_version: string;
            /** Prompt Hash */
            prompt_hash: string;
            /** Candidates */
            candidates?: components["schemas"]["CandidateOut"][];
            /** Error Code */
            error_code?: string | null;
            /** Started At */
            started_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * TraceEventOut
         * @description Evento de traza tipado (design §6.6); el resto de campos son datos.
         *
         *     ``extra="allow"``: cada evento lleva sus propios campos (provider, prompt_id,
         *     score_final, …) manteniendo ``ts``/``type`` como base del contrato.
         */
        TraceEventOut: {
            /** Ts */
            ts: string;
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisualElement
         * @description Elemento visual con vínculo obligatorio a la tesis (VIS-03).
         */
        VisualElement: {
            /** Element Id */
            element_id: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * VisualOut
         * @description Respuesta del flujo visual: contrato + metadatos del asset (§5.4).
         */
        VisualOut: {
            /** Thesis */
            thesis: string;
            /** Concept */
            concept: string;
            /** Elements */
            elements?: components["schemas"]["VisualElement"][];
            /** Alt Text */
            alt_text: string;
            /**
             * Status
             * @default VISUAL_DRAFT
             */
            status: string;
            /** Id */
            id: number;
            /** Candidate Id */
            candidate_id: number;
            /** Svg Path */
            svg_path?: string | null;
        };
        /**
         * VoiceProfileOut
         * @description Perfil de voz v0 PROVISIONAL (VOI-01): explícitamente no validado.
         */
        VoiceProfileOut: {
            /**
             * Version
             * @default v0
             */
            version: string;
            /**
             * Label
             * @default perfil de voz provisional v0
             */
            label: string;
            /**
             * Provisional
             * @default true
             */
            provisional: boolean;
            /** Rules */
            rules?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_demo_ideas_api_ideas_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoIdeaOut"][];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_brief_api_projects__project_id__brief_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_detail_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trace_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_run_api_runs__run_id__evaluate_post: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_projects__project_id__generate_post: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_generate_api_projects__project_id__retry_generate_post: {
        parameters: {
            query?: {
                provider?: string | null;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_candidate_api_candidates__candidate_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_revision_api_candidates__candidate_id__request_revision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_candidate_api_candidates__candidate_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_visual_api_candidates__candidate_id__visual_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_simulated_api_candidates__candidate_id__publish_simulated_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_visual_api_visuals__visual_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visual_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_visual_api_visuals__visual_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visual_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_visual_api_visuals__visual_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visual_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisualOut"];
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visual_svg_api_visuals__visual_id__svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visual_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description VALIDATION_ERROR: el request no cumple el contrato */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description NOT_FOUND: proyecto/run/candidato/visual inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STATE_TRANSITION_REJECTED: transición FSM ilegal, con el requisito faltante en el mensaje */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
